Add the default pygrc file to package_data list, so it gets installed properly.
Without this update, the pygrc file will be missing on a clean install,
resulting in a cryptic error message like

  ConfigParser.NoSectionError: No section: 'Memory'

when trying to import pygeode.